<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\v1\models\base;

use Yii;

/**
 * This is the base-model class for table "nurse".
 *
 * @property integer $id
 * @property integer $id_person
 * @property integer $file_number
 * @property integer $registration_number
 * @property string $date_of_admission
 * @property string $position
 *
 * @property \app\modules\v1\models\Person $person
 * @property \app\modules\v1\models\NurseSector[] $nurseSectors
 * @property string $aliasModel
 */
abstract class Nurse extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'nurse';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_person', 'file_number', 'registration_number'], 'integer'],
            [['date_of_admission'], 'safe'],
            [['position'], 'string', 'max' => 40],
            [['id_person'], 'exist', 'skipOnError' => true, 'targetClass' => \app\modules\v1\models\Person::className(), 'targetAttribute' => ['id_person' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_person' => 'Id Person',
            'file_number' => 'File Number',
            'registration_number' => 'Registration Number',
            'date_of_admission' => 'Date Of Admission',
            'position' => 'Position',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPerson()
    {
        return $this->hasOne(\app\modules\v1\models\Person::className(), ['id' => 'id_person']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNurseSectors()
    {
        return $this->hasMany(\app\modules\v1\models\NurseSector::className(), ['id_nurse' => 'id']);
    }




}
