<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\v1\models\base;

use Yii;

/**
 * This is the base-model class for table "nurse_unit".
 *
 * @property integer $id
 * @property integer $id_nurse
 * @property integer $id_unit
 * @property string $entry_date
 * @property string $exit_date
 * @property string $exit_cause
 *
 * @property \app\modules\v1\models\Nurse $nurse
 * @property \app\modules\v1\models\Unit $unit
 * @property string $aliasModel
 */
abstract class NurseUnit extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'nurse_unit';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_nurse', 'id_unit'], 'integer'],
            [['entry_date', 'exit_date'], 'safe'],
            [['exit_cause'], 'string'],
            [['id_nurse'], 'exist', 'skipOnError' => true, 'targetClass' => \app\modules\v1\models\Nurse::className(), 'targetAttribute' => ['id_nurse' => 'id']],
            [['id_unit'], 'exist', 'skipOnError' => true, 'targetClass' => \app\modules\v1\models\Unit::className(), 'targetAttribute' => ['id_unit' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_nurse' => 'Id Nurse',
            'id_unit' => 'Id Unit',
            'entry_date' => 'Entry Date',
            'exit_date' => 'Exit Date',
            'exit_cause' => 'Exit Cause',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNurse()
    {
        return $this->hasOne(\app\modules\v1\models\Nurse::className(), ['id' => 'id_nurse']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUnit()
    {
        return $this->hasOne(\app\modules\v1\models\Unit::className(), ['id' => 'id_unit']);
    }




}
