<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\v1\models\base;

use Yii;

/**
 * This is the base-model class for table "patient_admission".
 *
 * @property integer $id
 * @property string $admission_date
 * @property string $admission_hour
 * @property integer $id_patient
 * @property string $anamnesis
 * @property string $diagnostic
 * @property string $reason_for_admission
 * @property integer $internment
 * @property integer $internment_sector
 *
 * @property \app\modules\v1\models\Patient $patient
 * @property string $aliasModel
 */
abstract class PatientAdmission extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'patient_admission';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['admission_date', 'admission_hour'], 'safe'],
            [['id_patient', 'internment', 'internment_sector'], 'integer'],
            [['anamnesis', 'diagnostic', 'reason_for_admission'], 'string'],
            [['id_patient'], 'exist', 'skipOnError' => true, 'targetClass' => \app\modules\v1\models\Patient::className(), 'targetAttribute' => ['id_patient' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'admission_date' => 'Admission Date',
            'admission_hour' => 'Admission Hour',
            'id_patient' => 'Id Patient',
            'anamnesis' => 'Anamnesis',
            'diagnostic' => 'Diagnostic',
            'reason_for_admission' => 'Reason For Admission',
            'internment' => 'Internment',
            'internment_sector' => 'Internment Sector',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPatient()
    {
        return $this->hasOne(\app\modules\v1\models\Patient::className(), ['id' => 'id_patient']);
    }




}
