<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\v1\models\base;

use Yii;

/**
 * This is the base-model class for table "patient".
 *
 * @property integer $id
 * @property string $name
 * @property string $last_name
 * @property integer $id_number
 * @property string $gender
 * @property integer $age
 * @property integer $phone
 * @property string $address
 * @property string $state
 *
 * @property \app\modules\v1\models\PatientAdmission[] $patientAdmissions
 * @property \app\modules\v1\models\SocialSegurity[] $socialSegurities
 * @property string $aliasModel
 */
abstract class Patient extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'patient';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'last_name', 'id_number', 'gender', 'age'], 'required'],
            [['id_number', 'age', 'phone'], 'integer'],
            [['address'], 'string'],
            [['name'], 'string', 'max' => 80],
            [['last_name', 'state'], 'string', 'max' => 50],
            [['gender'], 'string', 'max' => 10]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'last_name' => 'Last Name',
            'id_number' => 'Id Number',
            'gender' => 'Gender',
            'age' => 'Age',
            'phone' => 'Phone',
            'address' => 'Address',
            'state' => 'State',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPatientAdmissions()
    {
        return $this->hasMany(\app\modules\v1\models\PatientAdmission::className(), ['id_patient' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSocialSegurities()
    {
        return $this->hasMany(\app\modules\v1\models\SocialSegurity::className(), ['id_patient' => 'id']);
    }




}
