<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\v1\models\base;

use Yii;

/**
 * This is the base-model class for table "person".
 *
 * @property integer $id
 * @property string $name
 * @property string $last_name
 * @property integer $id_number
 * @property integer $age
 * @property string $birth_date
 * @property integer $phone_number
 * @property string $email
 * @property string $gender
 *
 * @property \app\modules\v1\models\Nurse[] $nurses
 * @property string $aliasModel
 */
abstract class Person extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'person';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_number', 'age', 'phone_number'], 'integer'],
            [['birth_date'], 'safe'],
            [['name', 'last_name'], 'string', 'max' => 60],
            [['email'], 'string', 'max' => 30],
            [['gender'], 'string', 'max' => 3]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'last_name' => 'Last Name',
            'id_number' => 'Id Number',
            'age' => 'Age',
            'birth_date' => 'Birth Date',
            'phone_number' => 'Phone Number',
            'email' => 'Email',
            'gender' => 'Gender',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNurses()
    {
        return $this->hasMany(\app\modules\v1\models\Nurse::className(), ['id_person' => 'id']);
    }




}
