<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\v1\models\base;

use Yii;

/**
 * This is the base-model class for table "sector".
 *
 * @property integer $id
 * @property string $name
 * @property integer $enable
 *
 * @property \app\modules\v1\models\NurseSector[] $nurseSectors
 * @property string $aliasModel
 */
abstract class Sector extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sector';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['enable'], 'integer'],
            [['name'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'enable' => 'Enable',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNurseSectors()
    {
        return $this->hasMany(\app\modules\v1\models\NurseSector::className(), ['id_sector' => 'id']);
    }




}
