<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\v1\models\base;

use Yii;

/**
 * This is the base-model class for table "social_segurity".
 *
 * @property integer $id
 * @property integer $number
 * @property integer $id_patient
 * @property integer $active
 *
 * @property \app\modules\v1\models\Patient $patient
 * @property string $aliasModel
 */
abstract class SocialSegurity extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'social_segurity';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['number', 'id_patient', 'active'], 'integer'],
            [['id_patient'], 'exist', 'skipOnError' => true, 'targetClass' => \app\modules\v1\models\Patient::className(), 'targetAttribute' => ['id_patient' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'number' => 'Number',
            'id_patient' => 'Id Patient',
            'active' => 'Active',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPatient()
    {
        return $this->hasOne(\app\modules\v1\models\Patient::className(), ['id' => 'id_patient']);
    }




}
