<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\v1\models\base;

use Yii;

/**
 * This is the base-model class for table "unit".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $enable
 *
 * @property \app\modules\v1\models\NurseUnit[] $nurseUnits
 * @property string $aliasModel
 */
abstract class Unit extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'unit';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['description'], 'string'],
            [['enable'], 'integer'],
            [['name'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
            'enable' => 'Enable',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNurseUnits()
    {
        return $this->hasMany(\app\modules\v1\models\NurseUnit::className(), ['id_unit' => 'id']);
    }




}
